config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie, dependent: :destroy
  belongs_to :list
  
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, :scope =>[:list]
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks, dependent: :destroy
    has_many :movies, through: :bookmarks

    validates :name, uniqueness: true
    validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks

    validates :title, presence: true
    validates :title, uniqueness: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    def new
      @list = List.find(params[:list_id])
      @bookmark = Bookmark.new
    end

    def create
      @list = List.find(params[:id])
      @bookmark = Bookmark.new(bookmark_params)

       if @bookmark.save
        redirect_to @list, notice: "created"
       else
        render :new
       end
    end

    def destroy
      @bookmark = Bookmark.find(params[:id])
      @bookmark.destroy
      redirect_to @list
    end
    
    private

    def bookmark_params
      params.require(:bookmark).permit(:comment, :movie_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
      @lists = List.all
    end

    def show
      @list = List.find(params[:id])
    end

    def new
      @list = List.new
    end

    def create
      @list = List.new(list_params)
      @list.save

      redirect_to lists_path(@list)
    end
    
    private
    
    def list_params
      params.require(:list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :name %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div>
    <h1>Those are your movie lists</h1>

    <ul>
      <% @lists.each do |list| %>
        <li>
            <%=link_to list_path(list) do %>
                <%=  list.name  %>
            <% end %>
        </li>
      <% end %>
    </ul>
</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<%= link_to "add new movie",  new_list_bookmark_path(@list) %>